//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hobby
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hobby()
        {
            this.Selected = new HashSet<Selected>();
        }
    
        public int hobby_id { get; set; }
        public string hobby1 { get; set; }
        public string short_description { get; set; }
        public string photo { get; set; }
        public string information_link { get; set; }
        public int age_limit { get; set; }
        public Nullable<double> minimum_investment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selected> Selected { get; set; }
    }
}
