//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int id_progress { get; set; }
        public int id_job { get; set; }
        public int id_selected { get; set; }
    
        public virtual Jobs Jobs { get; set; }
        public virtual Selected Selected { get; set; }
    }
}
