//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selected
    {
        public int id_selected { get; set; }
        public int id_users { get; set; }
        public int id_hobby { get; set; }
        public int personal_assessment { get; set; }
    
        public virtual Hobby Hobby { get; set; }
        public virtual Progress Progress { get; set; }
        public virtual Users Users { get; set; }
    }
}
